# Generated by Django 3.2.8 on 2022-02-07 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='participant_id',
        ),
    ]
