# Generated by Django 3.2.8 on 2022-02-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220207_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='event_id',
        ),
    ]
